### ISSUE TITLE
blink-cocoa Crashing on Apple M1

### ISSUE THREAD

**Issue by dtcooper** [AGProjects/blink-cocoa#1]
Downloading the latest beta @ http://beta.icanblink.com/ on an Apple Macbook Air with an M1 (arm) chip, the app crashes.

Just wanted to create this ticket as a placeholder for that. Thanks for the great app!

**Comment by dtcooper** [comment]
Seems to be related to https://github.com/ronaldoussoren/pyobjc/issues/347

**Comment by adigeo** [comment]
https://lists.ag-projects.com/pipermail/blink/2021-February/date.html <https://lists.ag-projects.com/pipermail/blink/2021-February/date.html>

**Comment by dtcooper** [comment]
@adigeo Is there any instructions to build Blink locally, or run it from Python directly without XCode?

**Comment by adigeo** [comment]
https://github.com/AGProjects/blink-cocoa/blob/master/INSTALL.txt

**Comment by dtcooper** [comment]
I'm tracking https://github.com/ronaldoussoren/pyobjc/issues/347#issuecomment-786766464 and I observe the latest build still failing, but I'll sit tight in the case the recent fix has not yet been released as the beta. Thanks!

**Comment by dtcooper** [comment]
Working great on latest build!
