### ISSUE TITLE
custom ring_inbound sound

### ISSUE THREAD

**Issue by SniperRus** [AGProjects/blink-cocoa#11]
is it possible to change ring_inbound.wav file on another sound? Probably a settings window where user could choose whatever sound he want?
at least export sound folder - if app found sound folder in ~/.blink - the app will search custom audio in it?

**Comment by adigeo** [comment]
Yes, it is possible, you can use the preferences panel the change the sound file location

<img width="721" alt="Screen Shot 2023-06-16 at 19 07 25" src="https://github.com/AGProjects/blink-cocoa/assets/13014925/ab99096a-6857-4be4-8790-0b2875a303e0">
